<?php
if (isset($this->formName)) {
    $flashMessenger = $this->flashMessenger();
    if ($flashMessenger->hasMessages() || $flashMessenger->hasCurrentMessages()) {
        $messages = $flashMessenger->getMessages() + $flashMessenger->getCurrentMessages();
        foreach ($messages as $message) {
            if (!isset($message['form']) || $this->formName != $message['form']) {
                continue;
            }
            ?>

            <div class="alert alert-<?= $message['type'] ?>" role="alert">
                <i class="icon fa fa-<?= $message['icon'] ?: 'info' ?>"></i> <?= $this->translate($message['message']) ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <?php
        }
    }
} else {
    ?>
    <p>Missing form name</p>
    <?php
}
