<!-- Modal -->
<div id="modal-contact" class="modal fade">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="details">
                <div class="modal-header">
                    <h3 class="modal-title text-uppercase">
                        <strong id="contact-name"></strong>
                    </h3>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <h4><strong>Detalhes do contato</strong></h4>

                    <p><i class="material-icons">phone</i> <span id="contact-phone"></span></p>
                    <p><i class="material-icons">mail</i>  <span id="contact-email"></span></p>
                    <p><i class="material-icons">group</i>  <span id="contact-group"></span></p>
                </div>

            </div>
        </div>
    </div>
</div>